# Generated by Django 3.0.7 on 2020-06-19 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('price', models.IntegerField(max_length=6)),
                ('company_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pe', models.IntegerField(max_length=5)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
