# Generated by Django 3.0.7 on 2020-06-19 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('option_chains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('price', models.IntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pe', models.IntegerField()),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Chains',
        ),
    ]
