# Generated by Django 3.0.7 on 2020-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_chains', '0002_auto_20200619_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='pe',
            field=models.FloatField(),
        ),
    ]
