# Generated by Django 3.0.7 on 2020-06-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_chains', '0003_auto_20200619_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='price',
            field=models.FloatField(),
        ),
    ]
