# Generated by Django 3.0.7 on 2020-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_chains', '0005_auto_20200619_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='de',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chain',
            name='market_cap',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chain',
            name='percent_change',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
