# Generated by Django 3.0.7 on 2020-06-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_chains', '0004_auto_20200619_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=2, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
